/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum RetCode
{
  SUCCESS = 0,
  PARAMETER_ERROR = 1,
  INNER_ERROR = 2,
  UNKNOWN_ERROR = 3,
}
